### ISSUE TITLE
problem when wavepicker is calling pyqtgraph and pyside 

### ISSUE THREAD

**Issue by iceseismic** [miili/grapePicker#12]
Hi,  I'm hitting a problem immediately on the call to  wavepicker - as follows ;  any suggestions greatly appreciated !    

1 Trace(s) in Stream:
XX.GA04.10.HHZ | 2013-09-30T00:00:00.000000Z - 2013-09-30T23:59:59.600000Z | 2.5 Hz, 216000 samples

Traceback (most recent call last):
  File "pick_using_wavepicker.py", line 80, in <module>
    wavePicker(stream1)
  File "/usr/lib/python2.7/site-packages/wavePicker-0.1dev-py2.7.egg/wavePicker/wavePicker.py", line 35, in **init**
    self.setupUi(self)
  File "/usr/lib/python2.7/site-packages/wavePicker-0.1dev-py2.7.egg/wavePicker/mainWindow.py", line 240, in setupUi
    self.qtGraphLayout = GraphicsLayoutWidget(self.splitter_2)
  File "/usr/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsLayoutWidget.py", line 26, in **init**
    GraphicsView.**init**(self, parent)
  File "/usr/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 72, in **init**
    QtGui.QGraphicsView.**init**(self, parent)
TypeError: arguments did not match any overloaded call:
  QGraphicsView(QWidget parent=None): argument 1 has unexpected type 'PySide.QtGui.QSplitter'
  QGraphicsView(QGraphicsScene, QWidget parent=None): argument 1 has unexpected type 'PySide.QtGui.QSplitter'

**Comment by miili** [comment]
Looks like a problem with PySide. Did you check your pyside installation?
